### ISSUE TITLE
Documentation installs old version

### ISSUE THREAD

**Issue by reederda** [grindcrank/twitter_ebooks#10]
Following the documentation in README.md to set up a bot seems to install Mispy's version 3.1.6 bot with the deprecated API. Is there a new process that can be used?

**Comment by grindcrank** [comment]
Yes, just change the gem to twitter_ebooks_poll.

**Comment by grindcrank** [comment]
I will update the README.md at some time, but there is so much outdated stuff in there, it will take me a while.

**Comment by reederda** [comment]
Ah that makes sense. Got it, thanks!
