### ISSUE TITLE
Ranking keywords fails when using UTF-8

### ISSUE THREAD

**Issue by jajandio** [grindcrank/twitter_ebooks#6]
Hi, when I try to use a custom stopwords.txt for spanish (so it catches common words that use á, é, etc) I get the following error:

C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/nlp.rb:20:in `split': invalid byte sequence in UTF-8 (ArgumentError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/nlp.rb:20:in `stopwords'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/nlp.rb:155:in `stopword?'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/nlp.rb:90:in `block in keywords'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/nlp.rb:90:in `reject'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/nlp.rb:90:in `keywords'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/model.rb:192:in `consume_lines'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/model.rb:226:in `consume_all'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/twitter_ebooks-3.1.6/lib/twitter_ebooks/model.rb:40:in `consume_all'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/twitter_ebooks-3.1.6/bin/ebooks:118:in `consume_all'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/twitter_ebooks-3.1.6/bin/ebooks:408:in `command'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/twitter_ebooks-3.1.6/bin/ebooks:429:in `<top (required)>'
        from C:/Ruby24-x64/bin/ebooks:22:in `load'
        from C:/Ruby24-x64/bin/ebooks:22:in `<main>'

**Comment by grindcrank** [comment]
Apparently, your stop words fil

**Comment by grindcrank** [comment]
Apparently, your stop words file is not in UTF-8 encoding. Could you convert it (on Unixes, I would use iconv, on Windows some better text editors can do a "Save with encoding") to UTF-8 and try again?

**Comment by grindcrank** [comment]
Closed due to lacking feedback.
